### ISSUE TITLE
consider using the multiprocessing module to parallelize capa

### ISSUE THREAD

**Issue by garanews** [fireeye/capa#167]
## Summary

It would be useful to speed up the analysis running rules in parallel.

## Motivation

It's  really annoying to wait.

**Comment by williballenthin** [comment]
I agree that capa can take a while to complete its analysis, primarily because its doing a complete disassembly and emulation to reconstruct the code flow of the input program.

Unfortunately, the underlying code analysis engine is not easily parallelizable, due to the way it maintains shared state in a workspace. The upfront analysis cannot be distributed via multiprocessing.

The matching that capa does could be parallelized, as it operates function-by-function. However, this matching operation is currently fairly quick, and I believe that loading of the workspace in each subprocess will dominate the matching tasks. So, while we could maybe distribute the capa matcher via multiprocessing, it would be a complex job with probably low returns.

For these reasons, we don't plan to use multiprocessing with capa right now. If you're able to try out this strategy locally and demonstrate that it works well, we'd be happy to incorporate your enhancements!
