### ISSUE TITLE
Capa json output producing more capabilities

### ISSUE THREAD

**Issue by Dump-GUY** [fireeye/capa#198]
### Describtion
During testing of Capa standalone on Win7 and Win10, Capa is producing more detected Capabilities in Json output than in console output without argument or with -v or -vv

### Steps to Reproduce
Run standalone version capa-v1.0.0-win.exe on windows machine and compare detected Capabilities with mentioned arguments and with json output option.

**Expected behavior:**
Producing same results.

**Actual behavior:**
Console Output missing Capabilities.

### Versions
capa-v1.0.0-win.exe.zip -standalone version used on win7 64bit and WIN10 64 bit

### Additional information
I am inculding .zip file which contains tested malicious sample (Remcos), Capabilities produced by console output (in .txt file), Capabilities produced by json output (in .txt file) and Capabilities which are missing in console output (in .txt file).
Password .zip file:infected
[Evidences.zip](https://github.com/fireeye/capa/files/4973959/Evidences.zip)

**Comment by williballenthin** [comment]
this is because the json report includes matches of ["lib" rules](https://github.com/fireeye/capa-rules#library-rules). these are rules that are meant to be used by other rules, rather than displayed to the user. hence, they have `rule.meta.lib=True` and no namespace.

so, this might be initially surprising, but its expected behavior.

![image](https://user-images.githubusercontent.com/156560/88429755-6fb28800-cdb4-11ea-8230-35a2907801ca.png)
