### ISSUE TITLE
ida plugin: add progress bar for analysis

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#300]
consider showing a progress bar as capa analyzes the open database.

simple way: use `tqdm` to display the progress, like we do for the loading of rules.

pretty way: use qt to show a progress bar via the ui. just to flex.

**Comment by mike-hunhoff** [comment]
I made some "progress" 😉 here but unfortunately due to the single-threaded nature of IDA Pro I don't think a complete solution is possible without making the plugin multi-threaded. While this is an option it's probably not feasible for the `1.3.0` release.

Sample run from WIP branch https://github.com/fireeye/capa/tree/explorer_progress_bar:

![progress](https://user-images.githubusercontent.com/42192796/92756132-c31f6c00-f349-11ea-88d7-ccf67f00ccb0.PNG)

Feel free to play with the branch listed above. It's definitely a WIP and serves mostly as a PoC.

**Comment by mr-tz** [comment]
Here's another POC using IDA's waitbox feature. We may be able to implement this faster, but I only had time to come up with this POC: https://github.com/fireeye/capa/compare/ida/explorer-waitbox

![2020-09-14_12-40-04](https://user-images.githubusercontent.com/17606537/93076543-cc7d4100-f687-11ea-86da-393a1d001385.png)

See `python/examples/widgets/waitbox/show_and_hide_waitbox.py` in your IDADIR.

**Comment by mike-hunhoff** [comment]
Thanks to @mr-tz's suggestion we have a working progress indicator in #314 👍

**Comment by mike-hunhoff** [comment]
closed by #314
