### ISSUE TITLE
lib rules not included in scoped rules

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#398]
This was observed in https://github.com/fireeye/capa-rules/pull/225.

Thorough lints fail to validate lib rules, because we ignore "lib" rules here:
https://github.com/fireeye/capa/blob/20ce29b0333741c3f677fc501e3c7e34dc062077/capa/rules.py#L864-L879

Possible solutions:
- remove "lib" exclusion (easy, however, there may be undesired side-effects @williballenthin?)
- add `RuleSet.lib_rules` (not as easy)
- to only change the linter, set all rules' lib meta to False (hacky)

**Comment by mike-hunhoff** [comment]
This appears to be causing issues in the rule generator plugin as well e.g. when a user attempts to create a new `lib` rule the plugin cannot make a match because the rule isn't included in the final ruleset (as no dependencies yet exist):

With `lib: true`:

![Screen Shot 2021-01-21 at 2 03 28 PM](https://user-images.githubusercontent.com/42192796/105412498-148e1080-5bf2-11eb-8416-1070e9045c60.png)

Without `lib: true`:

![Screen Shot 2021-01-21 at 2 02 50 PM](https://user-images.githubusercontent.com/42192796/105412551-253e8680-5bf2-11eb-9fa7-5ba51d7b178c.png)

This also prevents existing `lib` rules with no dependencies from showing up in the rule generator under matched rules, even though these rules may match the current function.
