### ISSUE TITLE
explorer: run analyze once

### ISSUE THREAD

**Issue by Ana06** [fireeye/capa#546]
### Summary

Currently, it is needed to click `Analyze` in both Program Analysis and Rule Generator. It would be cool that it is only needed to run it once and appears in both views.

This would also allows us to run analyze by default when openning the explorer. In the way it is implemented now, we could run it for program analysis when the user only want to use the generator.

I wonder if this would allow us to remove the analyze button completely (is there a reason to want to analyze twice? :confused:)

### Motivation

I would like to save some clicks every time I open capa explorer.

### Describe alternatives you've considered

Adding an option to run the analysis in the program view when loading the capa explorer helps to automate opening capa explorer for program analysis and it is easy to implement (PR coming). But I think the propose in this issue is a better approach.

**Comment by mike-hunhoff** [comment]
Thank you for the feedback @Ana06! Originally we removed the functionality to automatically analyze because we had yet to implement a means for users to cancel the analysis (in case of long run times). We then realized that there may be some situations where a user may not want analysis to run automatically e.g. they only want to use the rule generator. There may also be instances where a user needs to run program analysis twice e.g. they've added a new rule(s) and need to run analysis again for the rule(s) to be included.

The reason for both program analysis and rule generator having `Analyze` buttons is because these buttons kick off two different types of analysis. The program analysis `Analyze` button kicks off analysis for the entire program loaded in IDA. The rule generator `Analyze` button kicks off analysis for **only** the function currently displayed in the IDA disassembly view (this speeds up analysis time significantly for the rule generator). The intention here is to give the user more control over which function is being analyzed by the rule generator, independently of the program analysis performed in the other tab.

**Comment by Ana06** [comment]
@mike-hunhoff thank you for the answer! 😉 This makes sense. Is there a way to indicate this to the user? I hadn't realised that in the rule generator the analysis is only done for the current function. Maybe we can make this more intuitive. What about changing `Analyze` by `Analyze current function` in the rule generator? 🤔

**Comment by mike-hunhoff** [comment]
I like `Analyze current function` but it feels a little long for a button name. What about `Generate` or something? This at least makes it apparent that it does something different from `Analyze`.

Unfortunately the `Analyze` button is a single button that programmatically follows different execution paths depending on the tab that is selected. So modifications to the button text will require a little more work on our end.
