### ISSUE TITLE
signature loading order and identified functions

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#656]
Prior loaded signatures seem to have preference. We load them alphabetically, so `flare_common` comes before the other ones.

This results in maybe less ideal results I've noticed in the below use case for PMA `Lab11-03.dll`

current order:
```
DEBUG:viv_utils.flirt:found library function: 0x1000178d: _Curl_hash_clean
```

loading common after vc32:
```
DEBUG:viv_utils.flirt:found library function: 0x1000178d: _exit
```

My suspicion is that `_exit` will likely be the better ID in most cases.

I propose to load in order:
1. vc32rtf
2. atlfmfc
3. common_libs

**Comment by williballenthin** [comment]
yikes, i didn't realize this could happen

as a counter point, i'd suggest that if we can't provide a concrete name, then we should maybe just use `??`

**Comment by mr-tz** [comment]
> as a counter point, i'd suggest that if we can't provide a concrete name, then we should maybe just use ??

that's a valid point, in IDA if a second signature is applied and the function was already identified no change happens.

**Comment by mr-tz** [comment]
@williballenthin any hints on implementing this? 😄

**Comment by williballenthin** [comment]
i'll look at this today or tomorrow so we can hopefully get it in by v2.0.

defining a load order of the FLIRT sigs is a little tricky because we dont have any place to store metadata, like signature priority. we could maybe load the signatures alphabetic sorted order, which is a hack but probably sufficient.

or, we could update the FLIRT matcher to recognize when a conflicting function is already marked as a library function to change the name to "??" rather than overwriting/ignoring it.

let me think about this a little bit.

**Comment by mr-tz** [comment]
prefixing to indicate priority would be the quickest fix:
something like:
```
00_vc32...
10_atlmfc...
20_common...
```

**Comment by williballenthin** [comment]
https://github.com/curl/curl/blob/52fab72397687467650093c86e5479cb1d759042/lib/hash.c#L223

![image](https://user-images.githubusercontent.com/156560/123827498-e823a200-d8bd-11eb-8de9-c3ea7f624e5a.png)

**Comment by williballenthin** [comment]
i'll address the immediate non-determinism issue by loading signatures in order according to their basename(filename).
